/**
 * reportService.ts
 *
 * Generates a Markdown project report from all analysis data stored in the DB.
 * No LLM — purely structured data formatted as clean Markdown.
 */

import { prisma } from "../database/db";

/**
 * generateProjectReport
 *
 * Fetches all analysis data for a project and renders a Markdown string.
 * Returns null if the project doesn't exist.
 */
export async function generateProjectReport(projectId: string): Promise<string | null> {
  const [project, stats, apis, dependencies, schema, backend, externalServices] = await Promise.all([
    prisma.project.findUnique({ where: { id: projectId } }),
    prisma.projectStats.findUnique({ where: { projectId } }),
    prisma.aPIEndpoint.findMany({ where: { projectId }, orderBy: { method: "asc" } }),
    prisma.dependency.findMany({ where: { projectId }, orderBy: { name: "asc" } }),
    prisma.schemaTable.findMany({ where: { projectId } }),
    prisma.backendInfo.findUnique({ where: { projectId } }),
    prisma.externalService.findMany({ where: { projectId } }),
  ]);

  if (!project) return null;

  const now = new Date().toISOString().split("T")[0]; // YYYY-MM-DD

  // ── Helpers ────────────────────────────────────────────────────────────

  const section = (title: string, content: string) =>
    `## ${title}\n\n${content.trim()}\n\n`;

  const table = (headers: string[], rows: string[][]): string => {
    const head = `| ${headers.join(" | ")} |`;
    const divider = `| ${headers.map(() => "---").join(" | ")} |`;
    const body = rows.map((r) => `| ${r.join(" | ")} |`).join("\n");
    return `${head}\n${divider}\n${body}`;
  };

  // ── Sections ───────────────────────────────────────────────────────────

  const header = `# ${project.name} — Codebase Report\n\n_Generated by Unwire AI on ${now}_\n\n---\n\n`;

  const overview = section(
    "Overview",
    [
      `| Property | Value |`,
      `| --- | --- |`,
      `| **Project** | ${project.name} |`,
      `| **Source** | ${project.sourceType === "github" ? `GitHub: ${project.githubUrl ?? "—"}` : "ZIP Upload"} |`,
      `| **Status** | ${project.status} |`,
      `| **Framework** | ${backend?.framework ?? "—"} |`,
      `| **Database** | ${project.stack.find((s) => ["MongoDB", "PostgreSQL", "MySQL", "SQLite", "Redis"].includes(s)) ?? "—"} |`,
      `| **Total Files** | ${stats?.filesCount ?? 0} |`,
      `| **API Endpoints** | ${stats?.apiCount ?? 0} |`,
      `| **Dependencies** | ${stats?.dependencyCount ?? 0} |`,
    ].join("\n")
  );

  const stackSection = section(
    "Technology Stack",
    project.stack.length > 0
      ? project.stack.map((s) => `- ${s}`).join("\n")
      : "_No stack detected._"
  );

  const architectureSection = section(
    "Architecture",
    backend?.requestFlow
      ? `**Request flow:** \`${backend.requestFlow}\``
      : "_Architecture data not available._"
  );

  // APIs
  const apisSection = section(
    "API Endpoints",
    apis.length > 0
      ? table(
          ["Method", "Endpoint", "File", "Auth"],
          apis.map((a) => [
            `\`${a.method}\``,
            `\`${a.path}\``,
            a.file || "—",
            a.authenticated ? "✓" : "—",
          ])
        )
      : "_No API endpoints detected._"
  );

  // Dependencies
  const runtimeDeps = dependencies.filter((d) => d.type === "runtime");
  const devDeps = dependencies.filter((d) => d.type === "dev");

  const depsContent = [
    runtimeDeps.length > 0
      ? `### Runtime Dependencies (${runtimeDeps.length})\n\n${table(
          ["Package", "Version"],
          runtimeDeps.map((d) => [d.name, d.version])
        )}`
      : null,
    devDeps.length > 0
      ? `### Dev Dependencies (${devDeps.length})\n\n${table(
          ["Package", "Version"],
          devDeps.map((d) => [d.name, d.version])
        )}`
      : null,
    runtimeDeps.length === 0 && devDeps.length === 0
      ? "_No dependencies detected._"
      : null,
  ]
    .filter(Boolean)
    .join("\n\n");

  const depsSection = section("Dependencies", depsContent);

  // External Services
  const extSection = section(
    "External Services",
    externalServices.length > 0
      ? table(
          ["Service", "Type", "Usages"],
          externalServices.map((s) => [s.name, s.type, String(s.usage)])
        )
      : "_No external services detected._"
  );

  // Database Schema
  const schemaContent =
    schema.length > 0
      ? schema
          .map(
            (t) =>
              `### ${t.tableName}\n\n${t.fields.map((f) => `- \`${f}\``).join("\n")}`
          )
          .join("\n\n")
      : "_No schema detected._";
  const schemaSection = section("Database Schema", schemaContent);

  // Backend details
  const backendSection = backend
    ? section(
        "Backend Details",
        [
          `| Property | Value |`,
          `| --- | --- |`,
          `| Framework | ${backend.framework} |`,
          `| Routes | ${backend.routes} |`,
          `| Controllers | ${backend.controllers} |`,
          `| Middleware | ${backend.middleware.join(", ") || "—"} |`,
        ].join("\n")
      )
    : "";

  const footer = `---\n\n_Report generated by [Unwire AI](https://unwire.ai) · ${new Date().toUTCString()}_\n`;

  return (
    header +
    overview +
    stackSection +
    architectureSection +
    apisSection +
    depsSection +
    extSection +
    schemaSection +
    backendSection +
    footer
  );
}
