/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServersIndexRouteImport } from './routes/servers.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ServersServerIdRouteImport } from './routes/servers.$serverId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as DeploymentsDeploymentIdRouteImport } from './routes/deployments.$deploymentId'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects.$projectId.index'
import { Route as ProjectsProjectIdServicesRouteImport } from './routes/projects.$projectId.services'
import { Route as ProjectsProjectIdDeploymentsRouteImport } from './routes/projects.$projectId.deployments'
import { Route as ProjectsProjectIdDeploymentRouteImport } from './routes/projects.$projectId.deployment'
import { Route as ProjectsProjectIdDependenciesRouteImport } from './routes/projects.$projectId.dependencies'
import { Route as ProjectsProjectIdDatabaseRouteImport } from './routes/projects.$projectId.database'
import { Route as ProjectsProjectIdChatRouteImport } from './routes/projects.$projectId.chat'
import { Route as ProjectsProjectIdBackendRouteImport } from './routes/projects.$projectId.backend'
import { Route as ProjectsProjectIdArchitectureRouteImport } from './routes/projects.$projectId.architecture'
import { Route as ProjectsProjectIdApisRouteImport } from './routes/projects.$projectId.apis'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIndexRoute = ServersIndexRouteImport.update({
  id: '/servers/',
  path: '/servers/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServersServerIdRoute = ServersServerIdRouteImport.update({
  id: '/servers/$serverId',
  path: '/servers/$serverId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeploymentsDeploymentIdRoute = DeploymentsDeploymentIdRouteImport.update({
  id: '/deployments/$deploymentId',
  path: '/deployments/$deploymentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdServicesRoute =
  ProjectsProjectIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDeploymentsRoute =
  ProjectsProjectIdDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDeploymentRoute =
  ProjectsProjectIdDeploymentRouteImport.update({
    id: '/deployment',
    path: '/deployment',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDependenciesRoute =
  ProjectsProjectIdDependenciesRouteImport.update({
    id: '/dependencies',
    path: '/dependencies',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdDatabaseRoute =
  ProjectsProjectIdDatabaseRouteImport.update({
    id: '/database',
    path: '/database',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdChatRoute = ProjectsProjectIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)
const ProjectsProjectIdBackendRoute =
  ProjectsProjectIdBackendRouteImport.update({
    id: '/backend',
    path: '/backend',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdArchitectureRoute =
  ProjectsProjectIdArchitectureRouteImport.update({
    id: '/architecture',
    path: '/architecture',
    getParentRoute: () => ProjectsProjectIdRoute,
  } as any)
const ProjectsProjectIdApisRoute = ProjectsProjectIdApisRouteImport.update({
  id: '/apis',
  path: '/apis',
  getParentRoute: () => ProjectsProjectIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/servers/$serverId': typeof ServersServerIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/projects/$projectId/apis': typeof ProjectsProjectIdApisRoute
  '/projects/$projectId/architecture': typeof ProjectsProjectIdArchitectureRoute
  '/projects/$projectId/backend': typeof ProjectsProjectIdBackendRoute
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/database': typeof ProjectsProjectIdDatabaseRoute
  '/projects/$projectId/dependencies': typeof ProjectsProjectIdDependenciesRoute
  '/projects/$projectId/deployment': typeof ProjectsProjectIdDeploymentRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/services': typeof ProjectsProjectIdServicesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/servers/$serverId': typeof ServersServerIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/servers': typeof ServersIndexRoute
  '/projects/$projectId/apis': typeof ProjectsProjectIdApisRoute
  '/projects/$projectId/architecture': typeof ProjectsProjectIdArchitectureRoute
  '/projects/$projectId/backend': typeof ProjectsProjectIdBackendRoute
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/database': typeof ProjectsProjectIdDatabaseRoute
  '/projects/$projectId/dependencies': typeof ProjectsProjectIdDependenciesRoute
  '/projects/$projectId/deployment': typeof ProjectsProjectIdDeploymentRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/services': typeof ProjectsProjectIdServicesRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/deployments/$deploymentId': typeof DeploymentsDeploymentIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteWithChildren
  '/servers/$serverId': typeof ServersServerIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/servers/': typeof ServersIndexRoute
  '/projects/$projectId/apis': typeof ProjectsProjectIdApisRoute
  '/projects/$projectId/architecture': typeof ProjectsProjectIdArchitectureRoute
  '/projects/$projectId/backend': typeof ProjectsProjectIdBackendRoute
  '/projects/$projectId/chat': typeof ProjectsProjectIdChatRoute
  '/projects/$projectId/database': typeof ProjectsProjectIdDatabaseRoute
  '/projects/$projectId/dependencies': typeof ProjectsProjectIdDependenciesRoute
  '/projects/$projectId/deployment': typeof ProjectsProjectIdDeploymentRoute
  '/projects/$projectId/deployments': typeof ProjectsProjectIdDeploymentsRoute
  '/projects/$projectId/services': typeof ProjectsProjectIdServicesRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/deployments/$deploymentId'
    | '/projects/$projectId'
    | '/servers/$serverId'
    | '/projects/'
    | '/servers/'
    | '/projects/$projectId/apis'
    | '/projects/$projectId/architecture'
    | '/projects/$projectId/backend'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/database'
    | '/projects/$projectId/dependencies'
    | '/projects/$projectId/deployment'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/services'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/deployments/$deploymentId'
    | '/servers/$serverId'
    | '/projects'
    | '/servers'
    | '/projects/$projectId/apis'
    | '/projects/$projectId/architecture'
    | '/projects/$projectId/backend'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/database'
    | '/projects/$projectId/dependencies'
    | '/projects/$projectId/deployment'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/services'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/deployments/$deploymentId'
    | '/projects/$projectId'
    | '/servers/$serverId'
    | '/projects/'
    | '/servers/'
    | '/projects/$projectId/apis'
    | '/projects/$projectId/architecture'
    | '/projects/$projectId/backend'
    | '/projects/$projectId/chat'
    | '/projects/$projectId/database'
    | '/projects/$projectId/dependencies'
    | '/projects/$projectId/deployment'
    | '/projects/$projectId/deployments'
    | '/projects/$projectId/services'
    | '/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DeploymentsDeploymentIdRoute: typeof DeploymentsDeploymentIdRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRouteWithChildren
  ServersServerIdRoute: typeof ServersServerIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  ServersIndexRoute: typeof ServersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/': {
      id: '/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof ServersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servers/$serverId': {
      id: '/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof ServersServerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deployments/$deploymentId': {
      id: '/deployments/$deploymentId'
      path: '/deployments/$deploymentId'
      fullPath: '/deployments/$deploymentId'
      preLoaderRoute: typeof DeploymentsDeploymentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/services': {
      id: '/projects/$projectId/services'
      path: '/services'
      fullPath: '/projects/$projectId/services'
      preLoaderRoute: typeof ProjectsProjectIdServicesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/deployments': {
      id: '/projects/$projectId/deployments'
      path: '/deployments'
      fullPath: '/projects/$projectId/deployments'
      preLoaderRoute: typeof ProjectsProjectIdDeploymentsRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/deployment': {
      id: '/projects/$projectId/deployment'
      path: '/deployment'
      fullPath: '/projects/$projectId/deployment'
      preLoaderRoute: typeof ProjectsProjectIdDeploymentRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/dependencies': {
      id: '/projects/$projectId/dependencies'
      path: '/dependencies'
      fullPath: '/projects/$projectId/dependencies'
      preLoaderRoute: typeof ProjectsProjectIdDependenciesRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/database': {
      id: '/projects/$projectId/database'
      path: '/database'
      fullPath: '/projects/$projectId/database'
      preLoaderRoute: typeof ProjectsProjectIdDatabaseRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/chat': {
      id: '/projects/$projectId/chat'
      path: '/chat'
      fullPath: '/projects/$projectId/chat'
      preLoaderRoute: typeof ProjectsProjectIdChatRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/backend': {
      id: '/projects/$projectId/backend'
      path: '/backend'
      fullPath: '/projects/$projectId/backend'
      preLoaderRoute: typeof ProjectsProjectIdBackendRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/architecture': {
      id: '/projects/$projectId/architecture'
      path: '/architecture'
      fullPath: '/projects/$projectId/architecture'
      preLoaderRoute: typeof ProjectsProjectIdArchitectureRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
    '/projects/$projectId/apis': {
      id: '/projects/$projectId/apis'
      path: '/apis'
      fullPath: '/projects/$projectId/apis'
      preLoaderRoute: typeof ProjectsProjectIdApisRouteImport
      parentRoute: typeof ProjectsProjectIdRoute
    }
  }
}

interface ProjectsProjectIdRouteChildren {
  ProjectsProjectIdApisRoute: typeof ProjectsProjectIdApisRoute
  ProjectsProjectIdArchitectureRoute: typeof ProjectsProjectIdArchitectureRoute
  ProjectsProjectIdBackendRoute: typeof ProjectsProjectIdBackendRoute
  ProjectsProjectIdChatRoute: typeof ProjectsProjectIdChatRoute
  ProjectsProjectIdDatabaseRoute: typeof ProjectsProjectIdDatabaseRoute
  ProjectsProjectIdDependenciesRoute: typeof ProjectsProjectIdDependenciesRoute
  ProjectsProjectIdDeploymentRoute: typeof ProjectsProjectIdDeploymentRoute
  ProjectsProjectIdDeploymentsRoute: typeof ProjectsProjectIdDeploymentsRoute
  ProjectsProjectIdServicesRoute: typeof ProjectsProjectIdServicesRoute
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
}

const ProjectsProjectIdRouteChildren: ProjectsProjectIdRouteChildren = {
  ProjectsProjectIdApisRoute: ProjectsProjectIdApisRoute,
  ProjectsProjectIdArchitectureRoute: ProjectsProjectIdArchitectureRoute,
  ProjectsProjectIdBackendRoute: ProjectsProjectIdBackendRoute,
  ProjectsProjectIdChatRoute: ProjectsProjectIdChatRoute,
  ProjectsProjectIdDatabaseRoute: ProjectsProjectIdDatabaseRoute,
  ProjectsProjectIdDependenciesRoute: ProjectsProjectIdDependenciesRoute,
  ProjectsProjectIdDeploymentRoute: ProjectsProjectIdDeploymentRoute,
  ProjectsProjectIdDeploymentsRoute: ProjectsProjectIdDeploymentsRoute,
  ProjectsProjectIdServicesRoute: ProjectsProjectIdServicesRoute,
  ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
}

const ProjectsProjectIdRouteWithChildren =
  ProjectsProjectIdRoute._addFileChildren(ProjectsProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DeploymentsDeploymentIdRoute: DeploymentsDeploymentIdRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRouteWithChildren,
  ServersServerIdRoute: ServersServerIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  ServersIndexRoute: ServersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
